global:
  params:
    p1: 10001
    p2: 20001

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    refresh:
      enabled: true
product:
  stock:
    alert-threshold: 10
  pricing:
    discount-rate: 0.15